FROM fdm1/base_python_dev

RUN apt-get install  -y python-numpy python-scipy \
                    python3-numpy python3-scipy \
                    libatlas-dev libatlas3gf-base \
                    python-matplotlib

RUN pip install scikit-learn && pip3 install scikit-learn
