FROM fdm1/base_python_dev:python2

RUN apt-get install -y python-numpy python-scipy \
                    libatlas-dev libatlas3gf-base \
                    python-matplotlib

RUN pip install scikit-learn && pip3 install scikit-learn
